<a href="https://colab.research.google.com/github/MdMuzammilBagwan/mozotech/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY  Tutorial

In [0]:
import numpy as np

The Basics

In [31]:
#Single dimension Array
a=np.array([1,2,3])
a.dtype="int16"
print(a)
print("2dimensional  Array")
b=np.array([[1,2,3],
            [1,2,4],
            [1,2,6]])
print(b)
print("Shape is:",b.shape,"this is ",b.ndim," Dim array",b.itemsize,"Size is")
print(a.dtype)
a.dtype

[1 0 0 0 2 0 0 0 3 0 0 0]
2dimensional  Array
[[1 2 3]
 [1 2 4]
 [1 2 6]]
Shape is: (3, 3) this is  2  Dim array 8 Size is
int16


dtype('int16')

Accesing changing specific element
rows
colums,etc

In [57]:
c=np.array([[1,3,4,5],
            [4,5,7,3]])
print(c)
print("for printing specific element ",c[0,3],c[0,:],c[:,2],c[:,3])
print(c[0,1:4:2])
print(c[1,2])
c[1,2]=12
print(c)
print(c[0,1:-1:2])
print(a)


[[1 3 4 5]
 [4 5 7 3]]
for printing specific element  5 [1 3 4 5] [4 7] [5 3]
[3 5]
7
[[ 1  3  4  5]
 [ 4  5 12  3]]
[3]
